spring.application.name=seat-booking-service

# 1. PostgreSQL Connection (The most important part)
# spring.datasource.url=jdbc:postgresql://localhost:5432/seatbooking?options=-c%20timezone=Asia/Kolkata
# spring.datasource.url=jdbc:postgresql://localhost:5432/seatbooking?serverTimezone=UTC
spring.datasource.url=jdbc:postgresql://localhost:5432/seatbooking?jdbcCompliantTruncation=false&preparedStatementCacheQueries=0&options=-c%20timezone=UTC
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate Settings
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Redis Connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 4. RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# These names tell our Java app which "box" to look at in RabbitMQ
seatbooking.rabbitmq.queue=payment_success_queue
seatbooking.rabbitmq.exchange=booking_exchange
seatbooking.rabbitmq.request-routing-key=payment.request
seatbooking.rabbitmq.success-routing-key=payment.success

# 5. Server Port
server.port=8080

spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-management=none

# Disable the Open-In-View warning
spring.jpa.open-in-view=false

seatbooking.lock.duration-minutes=2

logging.level.org.springframework.amqp=DEBUG

# Disable the automatic Docker Compose connection





# Keep the console output clean
# logging.level.org.hibernate.orm.jdbc.error=ERROR
